server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service_passenger_user?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: tiger
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
  application:
    name: service-passenger-user