server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
  application:
    name: api-passenger
  redis:
    host: 192.168.200.130
    port: 6379
    password: leadnews